# Porta do Servidor Tomcat exigida no teste
server.port=8082

# --- CONFIGURACAO TEMPORARIA (H2 EM MEMORIA) ---
spring.datasource.url=jdbc:h2:mem:mercado_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- CONFIGURACAO OFICIAL (ORACLE FIAP - COMENTADA) ---
# spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
# spring.datasource.username=rm563734
# spring.datasource.password=SUA_SENHA_AQUI
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Configuracoes de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true